# Generated by Django 4.0.5 on 2022-07-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeitem_api', '0002_employeeitem_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeitem',
            name='event',
        ),
    ]
