# Generated by Django 4.0.5 on 2022-07-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0005_remove_event_employeeitem'),
        ('employeeitem_api', '0003_remove_employeeitem_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeitem',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events_api.event'),
        ),
    ]
