# Generated by Django 4.0.5 on 2022-07-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeitem_api', '0004_employeeitem_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeitem',
            old_name='event',
            new_name='party',
        ),
    ]
